# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Ui_MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1920, 1080)
        self.action_Logout = QAction(MainWindow)
        self.action_Logout.setObjectName(u"action_Logout")
        self.action_Monitor_App = QAction(MainWindow)
        self.action_Monitor_App.setObjectName(u"action_Monitor_App")
        self.action_Monitor_App.setCheckable(True)
        self.action_MuckAnalysis_App = QAction(MainWindow)
        self.action_MuckAnalysis_App.setObjectName(u"action_MuckAnalysis_App")
        self.action_MuckAnalysis_App.setCheckable(True)
        self.action_VibrationAnalysis_App = QAction(MainWindow)
        self.action_VibrationAnalysis_App.setObjectName(u"action_VibrationAnalysis_App")
        self.action_VibrationAnalysis_App.setCheckable(True)
        self.action_Optimization_App = QAction(MainWindow)
        self.action_Optimization_App.setObjectName(u"action_Optimization_App")
        self.action_Optimization_App.setCheckable(True)
        self.action_Query_App = QAction(MainWindow)
        self.action_Query_App.setObjectName(u"action_Query_App")
        self.action_Query_App.setCheckable(True)
        self.action_Help = QAction(MainWindow)
        self.action_Help.setObjectName(u"action_Help")
        self.action_Help.setCheckable(True)
        self.action_About = QAction(MainWindow)
        self.action_About.setObjectName(u"action_About")
        self.action_Console = QAction(MainWindow)
        self.action_Console.setObjectName(u"action_Console")
        self.action_Console.setCheckable(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.mdiArea = QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName(u"mdiArea")
        self.mdiArea.setTabsClosable(True)

        self.verticalLayout.addWidget(self.mdiArea)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1920, 26))
        self.menu_General = QMenu(self.menubar)
        self.menu_General.setObjectName(u"menu_General")
        self.menu_Apps = QMenu(self.menubar)
        self.menu_Apps.setObjectName(u"menu_Apps")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QSize(40, 60))
        self.toolBar.setFloatable(True)
        MainWindow.addToolBar(Qt.LeftToolBarArea, self.toolBar)

        self.menubar.addAction(self.menu_General.menuAction())
        self.menubar.addAction(self.menu_Apps.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menu_General.addAction(self.action_Logout)
        self.menu_Apps.addAction(self.action_Monitor_App)
        self.menu_Apps.addAction(self.action_MuckAnalysis_App)
        self.menu_Apps.addAction(self.action_VibrationAnalysis_App)
        self.menu_Apps.addAction(self.action_Optimization_App)
        self.menu_Apps.addAction(self.action_Query_App)
        self.menu_Apps.addSeparator()
        self.menu_Apps.addAction(self.action_Console)
        self.menu_Help.addAction(self.action_Help)
        self.menu_Help.addAction(self.action_About)
        self.toolBar.addAction(self.action_Monitor_App)
        self.toolBar.addAction(self.action_MuckAnalysis_App)
        self.toolBar.addAction(self.action_VibrationAnalysis_App)
        self.toolBar.addAction(self.action_Optimization_App)
        self.toolBar.addAction(self.action_Query_App)
        self.toolBar.addAction(self.action_Console)
        self.toolBar.addAction(self.action_Help)
        self.toolBar.addAction(self.action_Logout)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"TBM\u667a\u80fd\u8f85\u52a9\u6398\u8fdb\u7cfb\u7edf", None))
        self.action_Logout.setText(QCoreApplication.translate("MainWindow", u"\u767b\u51fa", None))
        self.action_Monitor_App.setText(QCoreApplication.translate("MainWindow", u"\u6398\u8fdb\u72b6\u6001\u76d1\u63a7", None))
        self.action_Monitor_App.setIconText(QCoreApplication.translate("MainWindow", u"\u76d1\u63a7", None))
#if QT_CONFIG(tooltip)
        self.action_Monitor_App.setToolTip(QCoreApplication.translate("MainWindow", u"\u6398\u8fdb\u72b6\u6001\u76d1\u63a7", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_Monitor_App.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00TBM\u6398\u8fdb\u72b6\u6001\u76d1\u63a7\u7a97\u53e3", None))
#endif // QT_CONFIG(statustip)
        self.action_MuckAnalysis_App.setText(QCoreApplication.translate("MainWindow", u"\u6e23\u571f\u56fe\u50cf\u5206\u6790", None))
        self.action_MuckAnalysis_App.setIconText(QCoreApplication.translate("MainWindow", u"\u6e23\u571f", None))
#if QT_CONFIG(tooltip)
        self.action_MuckAnalysis_App.setToolTip(QCoreApplication.translate("MainWindow", u"\u6e23\u571f\u56fe\u50cf\u5206\u6790", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_MuckAnalysis_App.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00TBM\u6e23\u571f\u5206\u6790\u7ec4\u4ef6", None))
#endif // QT_CONFIG(statustip)
        self.action_VibrationAnalysis_App.setText(QCoreApplication.translate("MainWindow", u"\u5200\u76d8\u632f\u52a8\u5206\u6790", None))
        self.action_VibrationAnalysis_App.setIconText(QCoreApplication.translate("MainWindow", u"\u632f\u52a8", None))
#if QT_CONFIG(tooltip)
        self.action_VibrationAnalysis_App.setToolTip(QCoreApplication.translate("MainWindow", u"\u5200\u76d8\u632f\u52a8\u5206\u6790", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_VibrationAnalysis_App.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00TBM\u5200\u76d8\u632f\u52a8\u5206\u6790\u7ec4\u4ef6", None))
#endif // QT_CONFIG(statustip)
        self.action_Optimization_App.setText(QCoreApplication.translate("MainWindow", u"\u6398\u8fdb\u53c2\u6570\u4f18\u5316", None))
        self.action_Optimization_App.setIconText(QCoreApplication.translate("MainWindow", u"\u4f18\u5316", None))
#if QT_CONFIG(tooltip)
        self.action_Optimization_App.setToolTip(QCoreApplication.translate("MainWindow", u"\u6398\u8fdb\u53c2\u6570\u4f18\u5316", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_Optimization_App.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00TBM\u6398\u8fdb\u53c2\u6570\u4f18\u5316\u7ec4\u4ef6", None))
#endif // QT_CONFIG(statustip)
        self.action_Query_App.setText(QCoreApplication.translate("MainWindow", u"\u6570\u636e\u67e5\u8be2", None))
        self.action_Query_App.setIconText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
#if QT_CONFIG(tooltip)
        self.action_Query_App.setToolTip(QCoreApplication.translate("MainWindow", u"\u6570\u636e\u67e5\u8be2", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_Query_App.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6570\u636e\u67e5\u8be2\u7a97\u53e3", None))
#endif // QT_CONFIG(statustip)
        self.action_Help.setText(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
#if QT_CONFIG(tooltip)
        self.action_Help.setToolTip(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
#endif // QT_CONFIG(tooltip)
        self.action_About.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
#if QT_CONFIG(tooltip)
        self.action_About.setToolTip(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_About.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5173\u4e8eTBM\u667a\u80fd\u8f85\u52a9\u6398\u8fdb\u7cfb\u7edf", None))
#endif // QT_CONFIG(statustip)
        self.action_Console.setText(QCoreApplication.translate("MainWindow", u"\u63a7\u5236\u53f0", None))
        self.action_Console.setIconText(QCoreApplication.translate("MainWindow", u"\u7ec8\u7aef", None))
#if QT_CONFIG(tooltip)
        self.action_Console.setToolTip(QCoreApplication.translate("MainWindow", u"\u63a7\u5236\u53f0", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_Console.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u63a7\u5236\u53f0", None))
#endif // QT_CONFIG(statustip)
        self.menu_General.setTitle(QCoreApplication.translate("MainWindow", u"\u83dc\u5355", None))
        self.menu_Apps.setTitle(QCoreApplication.translate("MainWindow", u"\u529f\u80fd", None))
        self.menu_Help.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

